// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://me4s6danqbbcnlfelhozes7spi.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nvwo6vuf3feqvis5hvbohomzgm",
    "aws_cognito_identity_pool_id": "eu-west-1:4d35724a-f367-4c9f-87c7-33d34ea39237",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_bY5lrl6aZ",
    "aws_user_pools_web_client_id": "674s7nr34mth5ci3pnkpapom93",
    "oauth": {},
    "aws_mobile_analytics_app_id": "66a7f65cf259414483903f8053172e44",
    "aws_mobile_analytics_app_region": "eu-west-1"
};


export default awsmobile;
